name: Keep Supabase Alive
on:
  schedule:
    - cron: '0 0 * * 4' # Chạy vào 0h sáng thứ 5 hàng tuần
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/Post/select=*" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
